services:
  webapp:
    image: mywebapp-image:latest
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
      docker-file-watcher:
        condition: service_started
    volumes:
      - "./src:/home/application/app"
  docker-file-watcher:
    image: "rcdfs/docker-file-watcher:latest"
    container_name: "docker-file-watcher"
    configs:
    - source: docker-file-watcher.config
      target: /tmp/docker-file-watcher.config

    volumes:
    - "./docker-compose.yaml:/tmp/docker-compose.yaml:ro"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./src/:/watch:ro"

    restart: always

configs:
  docker-file-watcher.config:
    content: |
      webapp .*\.py
      another-service .*\.(css|js)
